# Generated by Django 6.0.2 on 2026-05-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='humidity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
