# Generated by Django 6.0.2 on 2026-03-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('data', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
            ],
        ),
    ]
