# Generated by Django 6.0.2 on 2026-03-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='probability',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
